### ISSUE TITLE
Waypoint only path not displaying

### ISSUE THREAD

**Issue by kposs** [LadyElyssa/LadyElyssaTacoTrails#14]
The Waypoints Only option does not display a pathway marker in game. A purple line is displayed only on the world map, but nothing is displayed once the map is closed. I have to constantly reopen world map to keep on course. I'm not sure if this is intentional? I've tried on Metricia Province, Caledon Forest, and Kessex Hills and none display a pathway.

**Comment by LadyElyssa** [comment]
Thank you for raising the issue and have pushed out a quick update that appears to fix the issues, please let me know if you continue to experience any problems.

Thank you.

**Comment by LadyElyssa** [comment]
Just to cover the seemingly obvious, are you running the latest version of Blish HUD?

**Comment by kposs** [comment]
I am running BlishHUD version 1.1.1 which is the latest.

I was in Bloodtide Coast and noticed the markers did not load. I completely exited the game and restarted, the markers appeared. I then ported to Caledon Forest and then were gone. I restarted the game again and they appeared. I ran into the Grove and then ran back out into Caledon Forest and they were gone again. It seems that the marker will only load for one map and not load again unless you restart the game.

**Comment by LadyElyssa** [comment]
Thanks for the follow up and sorry to hear you are still having problems.

I have just popped in to GW2 and put myself in to Bloodtide Coast and then loaded up Blish and everything appeared okay, went on to Caledon and trails showing ok, so I closed everything and then started Blish first and then GW2 and all appears okay here.

As it is BlishHud that renders the trails and markers, I would recommend going through their troubleshooting guide that you can read at: [https://blishhud.com/docs/user/troubleshooting/](https://blishhud.com/docs/user/troubleshooting/)

If their troubleshooting guide does not help then you might want to consider raising the issue on their github page here: [https://github.com/blish-hud/Blish-HUD/issues](https://github.com/blish-hud/Blish-HUD/issues) or alternatively, if you use Discord, you could talk with them there: [https://discord.gg/FYKN3qh](https://discord.gg/FYKN3qh) where you will likely receive a more personal and direct response.

Please do keep me updated on how you get on.
