### ISSUE TITLE
some notes from latest WC

### ISSUE THREAD

**Issue by bluenote73** [LadyElyssa/LadyElyssaTacoTrails#17]
Hey :) I did another world completion run and noted down paths that did not have return instructions.
Most of them are obvious, at least now that I'm a little familiar with how it is supposed to work. It was only when I had also made some mistake earlier that it was confusing initially.  If there's any here that don't seem right to you then put it down to my punchiness, I do this stuff in long sessions. 

- Vista north of cereboth WP in Kessex
- Forgepits POI in FGS 
- Alpenzure Cave POI in Wayfarer foothills
- Chantry of Secrets in bloodtide
- Rata Sum usability station
- Dawnside Quay
- Gates of Arah 

One thing that I found a little awkward was instances. After having my jade protocol buffs stripped I was quite gunshy and just left the cities for last, but I noted other places like Chantry of Secrets, Nolan's Hatchery, and um the instance in Straits of Devastation as throwing a bit of a wrench. I realize *now* that some you actually just hug the door ignoring the entry pop up, but some it seems one does need to enter. In a perfect world maybe an "enter" and "hug" icon or instruction, and/or instructions on where to go next in case one needs to skip it. TBH I'm not sure if jade protocol support is on your radar at all but I hope it is :) Once I started going out of order, or having to correct mistakes I made I did find the 'start' and 'finish' icons could be a bit more prominent so as to stand out.

I really appreciated the more simple approach vs some other packs so that even if something went wrong it was much easier than others to recover from. I hope not to do another WC soon but I'm definitely a fan of your pack for this and for its other features. thanks :)

**Comment by LadyElyssa** [comment]
Thank you so much for the amazing and detailed feedback along with the suggestions :o)

I'll be sure to take a look at the locations missing the return locations you provided, so thank you for pointing those out and my apologies for the omission making things more difficult than they needed to be. You are right to point out that some locations do not need to be entered, so I will see about trying to make it clear which ones do or do not need to be entered.

Aspects of the Jade Protocol can certainly be useful as demonstrated with [Tehs Trails](https://github.com/xrandox/TehsTrails) in their speed runs. I will take a look at the locations where it would be lost for those that might like to make use of it and, if nothing else, include a reminder and perhaps a WP link to refresh it.

**Comment by bluenote73** [comment]
That was fast :) My memory jogged for a couple other items - 
The Taidha covington pirate ship can be closed, and a path ends within with the Beckoning Force Hero Challenge and so somebody that is .. not in the groove (not mentioning any names) could be left outside wondering longer than strictly necessary :).  The instruction is just go back to laughing gull, but it could use a little "continue at laughing gull and come back later if closed" or something outside the compound.  Took me longer than most I guess to internalize 'follow back until the last branch as a general rule..' shrug :)

The other is more of a longer term and maybe philosophical thing - this last WC I decided to up my game be organized and put in buy orders for the TP heart items (first time I've tried to do this) but only a few came through. Some of them are like 6G at the moment to instant buy.  Some (even rudimentary) directions on how best to complete the hearts if one doesn't have the items would be useful at least IMO. I feel a bit guilty suggesting it as I guess it's a fair bit of work. Anyway, it's a thought.

**Comment by LadyElyssa** [comment]
Thanks again and didn't know about the pirate ship closing at Taidha, so looks like I have some loitering to do in case there is an alternative way of getting it done, if not then will follow your suggestion. I am also considering putting together a route for any do later parts.

I was quite surprised at the cost of some of the heart items myself and including trails for those hearts is a good idea and easy enough to add on to the existing heart trails and something to keep me busy for a while.

**Comment by LadyElyssa** [comment]
Applied with version 4.9.
