### ISSUE TITLE
Keyfarming

### ISSUE THREAD

**Issue by bluenote73** [LadyElyssa/LadyElyssaTacoTrails#20]
Hey Elyssa 
I noticed the improvements you did on the go/no go taking into consideration protocol buffs, thanks :) [the new heart paths reaaaaally make a difference for me].  I did my first keyfarm last night (no tomes guide) and coincidentally today I continued a world completion I started on my alt resuming at queensdale with your pack. I couldn't help but notice what a smoooooth fit a keyfarm category with the relevant hearts, WP instructions and + a few adventure guide prompts would be.  If it piqued your interest the one suggestion I have on improving crone's path is to include maybe the dodge chest circle for the dodge adventure guide bit.  
No worries if it's not of interest. Here's the guide I was looking at just in case:
https://youtu.be/KV1sku2Vu0A?si=_JIv0xM5rGch6j9I

On the off chance adding major city speed boon NPC's would be of interest to me too :)

**Comment by LadyElyssa** [comment]
Your timing is incredible as I have been working on a key farm route that currently focuses on the Human zone, though I do hope to do one for the other races for those that like to mix things up or who want some variety from time to time. It also includes trails for each of the story episodes all the way up to the level 40 and level 60 keys in addition to LWS2: Ep. 6, Tangled Paths and then on to HoT and working through to Chapter 11. Roots of Terror (unfortunately requires playing through all chapters to reach chapter 11) and includes notes for map completing the Orr maps, Dry, Top, Silverwastes, Bloodstone Fen and Grothmar Valley for a chance at some additional keys.

I have found the [speed boons](https://wiki.guildwars2.com/wiki/Speed_boons) page on the wiki and will have to get the locations marked down and then see how well they faactor in to the route(s).

Thank you for the video link. That was certainly an interesting approach to key farming by using the Character Adventure Guide and is certainly worth looking in to further.  While mounts have been a great addition, I still do most of my routes on foot and it would certainly be a good fit for F2P players, so is worth some serious consideration.

**Comment by bluenote73** [comment]
Oh wow what a coincidence :) I can't wait to try out some of that. What makes  the adventure-guide keyfarm attractive to me (and I imagine the appeal will be to some) is tomes are relatively less freely available since it's now 4 a month from weeklies unless one wants to pay AA for them which has an opportunity cost attached which (I think) makes using bought tomes to keyfarm probably not attractive. Granted launchies seem  to have stacks and stacks, but the newer one is the more dear they are. Looking forward to trying either way :)

**Comment by bluenote73** [comment]
You're amazing :) I'm going to try this ASAP :)
