### ISSUE TITLE
Unset Variable in Heart Code

### ISSUE THREAD

**Issue by execpanda** [LadyElyssa/LadyElyssaTacoTrails#22]
![image](https://github.com/LadyElyssa/LadyElyssaTacoTrails/assets/80188020/ee498a87-fded-4c8e-bb9f-926693ae8bd0)
as seen above this is a table ref that is not seen

**Comment by execpanda** [comment]
![image](https://github.com/LadyElyssa/LadyElyssaTacoTrails/assets/80188020/4cfc27f0-dfa9-4e50-a9cd-97c2234d5ae7)
another found, both in Met Province

**Comment by dlamkins** [comment]
Looks to be an issue I introduced in the pathing module with an incorrect decoding method.  https://github.com/dlamkins/TmfLib/commit/70a4758a165f1bd11e760e442202e64e339ca2c2#diff-7f173513cb714b00881e3a1f528c8a6a307b8452551ec8f98e1de9ea4b2781aaR88

**Comment by LadyElyssa** [comment]
Thanks for the headsup. I presume this will be fixed in due course or is there an alternative method for new lines now?

**Comment by dlamkins** [comment]
I'll have it fixed in an upcoming release.  There isn't an alternative at this time.  I'll post a note here once it is fixed.  👍

**Comment by LadyElyssa** [comment]
Thank you.
