### ISSUE TITLE
world complete notes

### ISSUE THREAD

**Issue by bluenote73** [LadyElyssa/LadyElyssaTacoTrails#31]
Hey :) I'm doing another map complete and your pack is making it sooo smooth. I notice the occasional niggle though. In case there's some other forum you'd want minor stuff like this sent to let me know. otherwise I'll record stuff as I come across it here. 
I'm at Crusader Soulhammer Hero Challenge and the guidance seems wrong or maybe reversed, I haven't listened but the answer is tribune.
![image](https://github.com/LadyElyssa/LadyElyssaTacoTrails/assets/6239498/4f6c9e9a-3fa3-4a9e-81c0-ae2f8c16aac0)
cheers :)

**Comment by LadyElyssa** [comment]
Glad to hear you are enjoying yet another map completion and thank you reminding me of this and seems Legionnaire was an old reference from the Ghosts of Ascalon, wo will get that corrected and updated.

**Comment by bluenote73** [comment]
I've been meaning to mention this one for a while but just never got around to creating an issue for it so it's a happy accident I've got one. I think these trails could be more visible with respect to indicating the direction. I find I have to stop or dismount and wait a second to detect the movement which isn't a big deal but isn't ideal when hurrying to try and find a bounty when initially finding the trail or when trails cross.

![image](https://github.com/LadyElyssa/LadyElyssaTacoTrails/assets/6239498/5fa72bd0-fa88-42a5-b712-078008bb3db3)

**Comment by LadyElyssa** [comment]
So, bounty trails too slow to be visible, which is a nice easy fix.

**Comment by bluenote73** [comment]
The logic here is a little unideal along the lines of the trails I pointed out before in shiverpeaks, where one may not be signaled to take the completion trail, and then all the ones you pass are rejoining, and so you never go to the completion until you realize something is amiss, backtrack and sort it out. I think the solve is, the yellow line should always rejoin blue before going into another heart zone, and all blues should start a yellow line within the heart boundary.
![image](https://github.com/LadyElyssa/LadyElyssaTacoTrails/assets/6239498/900a3f28-6cd3-4f85-8ed6-dbdbbc6e1aeb)

**Comment by LadyElyssa** [comment]
Thanks again for the great feedback and suggestions and that is a great guiding principle to adhere to.  Will be looking at that area today before I get back to working on the adventures.

**Comment by cah-kangkung** [comment]
Hello, i wonder is the core tyria trail can be done without skycale or griffon? @LadyElyssa

**Comment by LadyElyssa** [comment]
Thank you for your question.

Most of the trails can be simply followed without the need for mounts but there are a number of places where mounts are currently used to help smooth the journey. I am due to revisit those trails and will look at areas where an alternative foot trail could be included.

**Comment by bluenote73** [comment]
The blue trail never triggers this heart notification at all
![image](https://github.com/LadyElyssa/LadyElyssaTacoTrails/assets/6239498/3bf7e0ca-f024-4044-940b-7b5af3db312f)

**Comment by LadyElyssa** [comment]
Thank you for letting me know and I have done a quick update on that one.

**Comment by bluenote73** [comment]
The loop and/or POI marker needs to move over just a bit. you can see where I looped to trigger it
![image](https://github.com/LadyElyssa/LadyElyssaTacoTrails/assets/6239498/40d7daf5-b784-410d-aee8-65865f8a51d1)

**Comment by bluenote73** [comment]
One will miss the southerly heart zone if one finishes early and takes the other path. Also fwiw you can cheese the treasure chest moa thing if your inventory is full for the Admiral Clarinda heart. I dunno if that fits your aesthetic though.
![image](https://github.com/LadyElyssa/LadyElyssaTacoTrails/assets/6239498/c95516ff-aa8f-4888-88f2-098d98ad5baf)

**Comment by LadyElyssa** [comment]
Wow, you have been busy and made some great progress! Thanks for sharing those details, will look in to sorting those out today!

**Comment by digitalmayhemx** [comment]
I'm doing map completion in Crystal Oasis and noticed that the trail completely misses a few points of interest and a vista.

Vista:
Omiramba Sand Sea Vista near [Retreat of the Resolute](https://wiki.guildwars2.com/wiki/Retreat_of_the_Resolute)
![northern waystation](https://github.com/LadyElyssa/LadyElyssaTacoTrails/assets/20528554/b5a98fa1-e9d6-47c4-b042-6918e9de18f8)

POIs:
[Sanctum of Nabkha](https://wiki.guildwars2.com/wiki/Sanctum_of_Nabkha)
![sanctum of nabkha](https://github.com/LadyElyssa/LadyElyssaTacoTrails/assets/20528554/26ccca3a-c2a1-4642-a455-59ef349fa8ac)

[Crucible of Consecration](https://wiki.guildwars2.com/wiki/Crucible_of_Consecration)
![crucible of concecration](https://github.com/LadyElyssa/LadyElyssaTacoTrails/assets/20528554/51d7ea1d-4a3c-4451-97e2-066cc14d6d7a)

[Retreat of the Resolute](https://wiki.guildwars2.com/wiki/Retreat_of_the_Resolute)
![retreat of the resolute](https://github.com/LadyElyssa/LadyElyssaTacoTrails/assets/20528554/fda9f8e8-d93d-4e95-9ca2-6d53d1dadf61)


Additionally, the path doesn't appear to go quite close enough to [Northern Way Station](https://wiki.guildwars2.com/wiki/Northern_Way_Station) to trigger
![sanctum of nabkha](https://github.com/LadyElyssa/LadyElyssaTacoTrails/assets/20528554/26ccca3a-c2a1-4642-a455-59ef349fa8ac)

**Comment by LadyElyssa** [comment]
Thank you for the concise screenshots and will take a look.

**Comment by bluenote73** [comment]
> I know Teh's Trails uses quite a few skips to cheese some of the hearts and don't personally uses the inventory full one as I don't see it as keeping with the spirit of things.

No problem, I sort of thought so but wanted to be sure.  I'm done now and I didn't make a note at the time, but the Vizier's tower stands out in my mind as a spot that could be improved but this might be more personal preference on my part. One can grab the POI by running up the stairs (at ground level, around the other side, so you're actually grabbing the POI from underneath) and then skyscale up the tree to cheese the jumping to grab the vista and HP.  If anything else comes to mind I'll let you know. Thanks for being so great about all the updates. 
![image](https://github.com/LadyElyssa/LadyElyssaTacoTrails/assets/6239498/59e8b31d-b4f3-414e-988b-596fee7f5da7)

**Comment by LadyElyssa** [comment]
Thanks again for your efforts and great feedback as always, it truly is a treasure and thank you for the Vizier Tower suggestion I will look in to that, I presume its a matter of simply getting enough height to be able to glide to the finish?

The original map completion route was devised by [LAW] : Lulle's Advanced World-Completion Guide and is the same route that Teh's Trails follows but I found this required a lot more map hopping. After some experimentation I came up with the route I use in my pack as it not only transitions nicely from map to map but can also be used with a new character, so long as they take a little more time to do some additional events and remember to gear up along the way, it will get them a good proportion of the way to lvl 80.

I have always liked finishing with the Orr Maps as I find them a real pleasure to complete, even though I still have characters without 100% map completion, they have all completed the Orr Maps.

**Comment by bluenote73** [comment]
Right, I realized you were considering new characters when I entered Lions Arch. That reminds me, I think there should be a 'start' or a path from the normal entry point in addition to the "first time in LA huh?" spot. IIRC that's from coming in from... the priory side?

Here's the vizier's stuff. The POI is up these stairs: 
![image](https://github.com/LadyElyssa/LadyElyssaTacoTrails/assets/6239498/453b8a35-a1f8-48f1-a1e4-73a459e9493d)

And here is tree to perch on to get to the top
![image](https://github.com/LadyElyssa/LadyElyssaTacoTrails/assets/6239498/e20eff5c-6928-4cfd-936f-56edaa3865f3)

**Comment by LadyElyssa** [comment]
Thank you for taking the time to explain more and for posting images to help clarify things. I will have to see about adding in shortcut trail.

You have a good point for those that may have already been there arriving from Lornar's and even though the Starting point is marked, I think a WP marker might be helpful to get people started.
