### ISSUE TITLE
Trail color guide?

### ISSUE THREAD

**Issue by jgentil** [LadyElyssa/LadyElyssaTacoTrails#32]
Is there a guide or really simple infographic that explains what trails are which color?

**Comment by LadyElyssa** [comment]
Thank you for your question, there is no single guide or infographic for this, however I can summarise most of them here for you, for reference.

Adventures - White and use a smaller triangular marker for the adventure and a dotted line leading to the adventure.
Dragonite - Blue
Festivals - These are typically themed by the Festival
   * Race = Yellow
   * Foot Race = White

Gathering - Similar to the Ore or Map Resource colour and typically have the main colour on the outside edge of the trail with a darker centre.
Guild Bounty - Green
Guild Trek = Tan
Hero Points - Green and use a Hero Point styled trail
Jumping Puzzles - White
Jumping Puzzle Shortcuts - Yellow
Map Mastery Insights - These match the expacs and use a Mastery styled trail
   *  HoT = Green
   * PoF = Purplish-Red
   * EoD = Blue
   * SotO= Gold

Map Completion
   * Core - Light Blue / Teal 
   * Heart Trails - Yellow
   * Expansions - Yellow, will be changed to Light Blue / Teal in next update for consistency
   * Dry Top & Silverwastes - Gold, will be changed to Light Blue / Teal in next update for consistency

Map Comnpletion (Waypoints Only) - Purple and different marker shape
Mini Dungeons - Silver and Chevron trail
World Bosses - Light Orange

I think that is all the main trail colours and I hope that helps. I am open to suggestions ifyou have any?
