### ISSUE TITLE
New map complete placeholder

### ISSUE THREAD

**Issue by bluenote73** [LadyElyssa/LadyElyssaTacoTrails#33]
I'm starting a new map completion (on my alt of all crazy things) and if I have an issue already created it's more likely I'll use it rather than skipping over anything that should be noted. Of course the pack is so smooth now (just did the first 4 cities because I'm getting any instances out of the way first so as to be able to use jade protocols) I'm not even sure I will have any notes :)  Anyway cheers to you for your excellent pack :)

**Comment by bluenote73** [comment]
Ok here's one. These are scattered around but they're so minor it didn't occur to me to make a note previously.
this is in metrica
![image](https://github.com/user-attachments/assets/43de743d-f8d0-4b76-9d56-346dad3f5a6a)

**Comment by LadyElyssa** [comment]
Oh that is weird as that looks like an issue for an older version of Blish HUD. If you right clich on the Blish Golem icon is there an update? If you left click on the Blish Golem icon, does it show in the bottom right hand corner as v1.1.1?

This is how the same heart info looks for me:
![image](https://github.com/user-attachments/assets/b8092f53-4fb1-4f66-9fc3-13aa348c2524)

**Comment by bluenote73** [comment]
Thanks, I'm sending it to blish hud discord since it seems to be a bug. I'm on newest of both
![image](https://github.com/user-attachments/assets/266b8303-7b1f-4aba-ab92-3cdfa7b0643b)

**Comment by LadyElyssa** [comment]
Ohh, so you are running one of their pre-release builds...

**Comment by bluenote73** [comment]
The heart tip says 'pile of metal scrap x 20' but its actually piece of char scrap metal', vanguard scout holt heart in fields of ruin
![image](https://github.com/user-attachments/assets/b54d2be9-2691-4520-a4f1-12df2a337004)

**Comment by bluenote73** [comment]
Help Roskos Ranchers heart is I think missing a return instruction at the end of the blue line (at the hero point)

**Comment by bluenote73** [comment]
Peaceful ogres of degun shun, talk to unskilled raptors - 3 is the wrong response, it's 2, then claws?
![image](https://github.com/user-attachments/assets/ca6e47ed-8c1b-4350-9377-71cc7ebeac87)

**Comment by LadyElyssa** [comment]
Thanks for catching those, will take a look at those today.

**Comment by LadyElyssa** [comment]
> Help Roskos Ranchers

This isn't normally completed before the HP but have added in a Waypoint Reminder there anyway for those that might already have had it partially completed.

> Peaceful ogres of degun shun, talk to unskilled raptors - 3 is the wrong response, it's 2, then claws? This actually might be random, or sequenced, I'm not sure, but I got different results.

Have taken another look at this heart and seems that it does depend / change though is alwaya a threatening action, so will have to leave this one as just Talk to Unskilled Raptors I think...

**Comment by bluenote73** [comment]
I was just coming here to post what the wiki said, and was wondering how I missed that it had the answers last night :)
Nice catch :)

**Comment by bluenote73** [comment]
This one is maybe nitpicky and debatable but I'll mention it as far as polishing. The routing here at stromkarl waypoint for help keep stromkarl safe heart I think could be made a bit more clear as the return path shows up before the leave path.
![image](https://github.com/user-attachments/assets/c3b15c71-5561-4323-a7e9-5d34e945378f)

**Comment by LadyElyssa** [comment]
Now this heart is a bit of a conundrum. Ideally, after coming out of the cave after doing the Skritt Heart it would be better to follow the heart path anti-clockwise but this goes against one of my un-written rules that if there is a waypoint nearby, which in this case requires going left out of the cave.

Any suggestions on a better way are most welcome.

**Comment by bluenote73** [comment]
I'm sure I can come up with a suggestion on the heart trail rather than changing the path. I'll go back soon. 
This is Bogside Camp WP and I miss it every time because it's hidden. I think this could get the same treatment you give POI's sometimes by emphasizing that we're picking up something at the point. 
![image](https://github.com/user-attachments/assets/745bf49c-3dc2-4c41-9a4d-e02bb610b6df)

**Comment by bluenote73** [comment]
I think I may have mentioned this before so I might be missing something. I think you don't get this POI if you follow the heart path. (Jinotl deadgrounds)
![image](https://github.com/user-attachments/assets/46ae37bf-3af8-4b27-a117-c4544b4f3127)

**Comment by LadyElyssa** [comment]
That's odd as you mentioned it back in this previous post
https://github.com/LadyElyssa/LadyElyssaTacoTrails/issues/31

I remember that only way to get it if needing the heart was to go in through the west gate, so noy sure what happened there as the other change you had previously picked up in Sparkfly around Leeshore Gauntlet went through ok, si it's been done, again :o)

![image](https://github.com/user-attachments/assets/5f04cffa-39d5-4ee5-b70a-65c58f4013a9)

**Comment by bluenote73** [comment]
This guys event is not always up and he just thanks you if it isn't. I think this could use a 'wait for event/kill stuff' instruction or a separate backup heart trail
![image](https://github.com/user-attachments/assets/bc2cdf29-3787-443b-8f7c-ab008d1fd662)

**Comment by bluenote73** [comment]
I might regret passing this on, but both keys work and one is really cheap
![image](https://github.com/user-attachments/assets/6b532ca4-3677-4693-aaa7-c07b3294168a)

**Comment by LadyElyssa** [comment]
Looks like a discrepency in the way the text is handled between Blsh and TacO, seems TacO will let me add additional text as you draw closer to the NPC, whereas Blish relpaces the info text, so I will have to reduce this to once reference.

Now looks like this on TacO
![image](https://github.com/user-attachments/assets/d38cdf59-441e-462b-9bad-918429119b34)

and like this on Blish
![image](https://github.com/user-attachments/assets/d5e4965c-d8bc-4951-badd-6fa59e71eb44)

**Comment by bluenote73** [comment]
I'm not sure we're talking about the same thing, I'm saying that if you didn't buy the roots , and the event is not up, it's not clear that the heart completion trail can't be done because the player does not know that it depends on the event.  I'm suggesting a second later completion trail and some kind of clarifying text
![image](https://github.com/user-attachments/assets/c73662b2-0c5f-41cd-90fe-f9cd9570ed57)

**Comment by LadyElyssa** [comment]
![image](https://github.com/user-attachments/assets/b35a7569-dc28-4c3d-8e68-1c018d23ead7)

**Comment by bluenote73** [comment]
The viziers tower JP shortcut, skyscale icon? to signal why one might want to take that path? or maybe there's already precedent that that type of line is a shortcut? if so I guess that makes sense and I think I may have seen one or two before
![image](https://github.com/user-attachments/assets/df1e02a6-019d-4d4f-8747-55a57d690eee)

**Comment by LadyElyssa** [comment]
Yes, the dotted / dashed line tends to signify a shortcut or an alternate route if there is a potential for the main route to become blocked. An example of this that I can think of is at Stonecrag Kraal on the East side of Plains of Ashford where the gates close during the event.

**Comment by bluenote73** [comment]
I went back to stromkarl as promised, and started at it until i realized I couldn't orient myself because you had already come up with a fix :)  And that's it for this map complete, ty :)

**Comment by LadyElyssa** [comment]
Congrats on another successfull map complete and thanks again for the suggestions and valuable feedback.
