### ISSUE TITLE
HOT completion

### ISSUE THREAD

**Issue by bluenote73** [LadyElyssa/LadyElyssaTacoTrails#34]
As far as I can tell there's a path missing consisting of at least a few POI's, passing through hidden copse / thistlevine
That's me using tekkit's to find the POI's I was missing at the end

![image](https://github.com/user-attachments/assets/c1f53f91-6fb2-4265-a5df-c668d45fd02b)

**Comment by LadyElyssa** [comment]
Thanks for letting me know.

Have replaced the missing trail, not sure what happened there as the WP marker was still where the trail would have ended. Weird...
