### ISSUE TITLE
map completion EOD

### ISSUE THREAD

**Issue by gartkb** [LadyElyssa/LadyElyssaTacoTrails#35]
Hey :) the path that expects one to be teleported to near the entrance to zen daijun IMO needs either an instruction "like, wait here to fully die" or something OR some sort of indicator that you were supposed to end up at that next trail.  Oops, terrible picture. But I hope you know what I mean :)
![image](https://github.com/user-attachments/assets/21735e34-9101-4936-8dec-dd087a00b7d9)

**Comment by LadyElyssa** [comment]
Thank you very much for the great suggestion, I will get that added.
